### ISSUE TITLE
Finalising 

### ISSUE THREAD

**Issue by eddelbuettel** [JohnRMoreau/2016-04-07-FederalReserveBoard#1]
We should look into finalising this.   Can you give me commit access?   

A process which has worked well for me in several different projects is mutual / symmetric branching and merging.  Ie for bigger changes either one of us could then branch, make changes and propose a PR which the other glances over.   Small and trivial changes like typos can still be done directly.

**Comment by JohnRMoreau** [comment]
Process - Agreed
Access - Granted
